application: landing-page
version: 1
runtime: python27
api_version: 1
threadsafe: true

skip_files:
- \.gitignore
- ^\.git/.*

handlers:
- url: /assets
  static_dir: assets
- url: /customizer
  static_dir: customizer
- url: /.*
  static_files: html/index.html
  upload: html/index.html